blank_issues_enabled: true
contact_links:
  - name: LiveVite Discussions
    url: https://github.com/Valian/live_vite/discussions
    about: Please ask and answer questions here
  - name: LiveVite Documentation
    url: https://hexdocs.pm/live_vite
    about: Check out the official documentation