import fs from "fs"
import { resolve } from "path"
import type { Component } from "vue"
import { migrateToLiveViteApp } from "./app.js"
import type { LiveViteOptions } from "./types.js"
import type { FrameworkRenderer } from "./renderer.js"
import type { RendererEntry } from "./hooks.js"
import { createVueRenderer, type VueSetupFn } from "./renderers/vue.js"

type Components = Record<string, Component>
type Manifest = Record<string, string[]>

/**
 * Creates a server-side render function using any FrameworkRenderer.
 *
 * The renderer must implement `renderToString`. This is the framework-agnostic
 * alternative to `getRender` (which is Vue-specific).
 *
 * @param renderer - A FrameworkRenderer with renderToString implemented
 * @param resolve - Component resolver function (name -> component)
 */
export const getRendererRender = (
  renderer: FrameworkRenderer,
  resolve: (name: string) => Promise<unknown> | unknown,
) => {
  if (!renderer.renderToString) {
    throw new Error(`Renderer "${renderer.name}" does not support server-side rendering`)
  }

  return async (name: string, props: Record<string, any>, slots: Record<string, string>) => {
    const component = await resolve(name)
    return renderer.renderToString!({ component, props, slots })
  }
}

/**
 * Creates a server-side render function that dispatches to the correct renderer
 * based on the `framework` argument.
 *
 * This mirrors `getMultiRendererHook` for the SSR side. Each renderer entry
 * provides a renderer (with `renderToString`) and a component resolver.
 *
 * If only one renderer is registered, the `framework` argument is optional
 * and the single renderer is used as a fallback.
 *
 * @param renderers - Map of framework name -> { renderer, resolve }
 */
export const getMultiRendererRender = (
  renderers: Record<string, RendererEntry>,
) => {
  const rendererNames = Object.keys(renderers)

  // Validate that all renderers support SSR
  for (const [name, entry] of Object.entries(renderers)) {
    if (!entry.renderer.renderToString) {
      throw new Error(`Renderer "${name}" does not support server-side rendering`)
    }
  }

  return async (name: string, props: Record<string, any>, slots: Record<string, string>, framework?: string) => {
    let entry: RendererEntry

    if (framework && renderers[framework]) {
      entry = renderers[framework]
    } else if (!framework && rendererNames.length === 1) {
      entry = renderers[rendererNames[0]]
    } else {
      const available = rendererNames.join(", ")
      throw new Error(
        framework
          ? `Unknown framework "${framework}" for SSR. Registered renderers: ${available}`
          : `Missing framework for SSR. Registered renderers: ${available}`
      )
    }

    const component = await entry.resolve(name)
    return entry.renderer.renderToString!({ component, props, slots })
  }
}

export const getRender = (componentsOrApp: Components | LiveViteOptions, manifest: Manifest = {}) => {
  const { resolve, setup } = migrateToLiveViteApp(componentsOrApp)

  // Adapt the LiveViteApp setup (object arg) to the VueSetupFn (positional args)
  const vueSetup: VueSetupFn = (makeApp, component, props, slots, plugin, el, ssr) =>
    setup({ createApp: makeApp, component, props, slots, plugin, el, ssr })

  const renderer = createVueRenderer({ setup: vueSetup, manifest })
  return getRendererRender(renderer, resolve)
}
/**
 * Loads the manifest file from the given path and returns a record of the assets.
 * Manifest file is a JSON file generated by Vite for the client build.
 * We need to load it to know which files to preload for the given page.
 * @param path - The path to the manifest file.
 * @returns A record of the assets.
 */
export const loadManifest = (path: string): Record<string, string[]> => {
  try {
    // it's generated only in prod build
    const content = fs.readFileSync(resolve(path), "utf-8")
    return JSON.parse(content)
  } catch (e) {
    // manifest is not available in dev, so let's just ignore it
    return {}
  }
}
